FROM nginx:stable-alpine
COPY replace_placeholder.sh /
COPY compiled /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80

ENTRYPOINT [ "sh", "/replace_placeholder.sh" ]
CMD ["nginx", "-g", "daemon off;"]
