import { APP_ID, LOCALE_ID, NgModule, inject, provideAppInitializer } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { registerLocaleData } from '@angular/common';
import localeDe from '@angular/common/locales/de';
import { FaIconLibrary } from '@fortawesome/angular-fontawesome';
import { PlotlyViaCDNModule } from 'angular-plotly.js';
import Aura from '@primeng/themes/aura';
import {
  faAddressBook,
  faUser,
  faXmarksLines,
  faArrowLeft,
  faArrowDown,
  faArrowUp,
  faAsterisk,
  faVcard,
  faBars,
  faBirthdayCake,
  faBlog,
  faBookOpen,
  faBuilding,
  faCalendarAlt,
  faChartLine,
  faCheck,
  faCheckCircle,
  faCircle,
  faClock,
  faKey,
  faCog,
  faConciergeBell,
  faCopy,
  faDatabase,
  faDollarSign,
  faDoorClosed,
  faDotCircle,
  faDownload,
  faEdit,
  faEllipsisH,
  faEnvelope,
  faExclamation,
  faExclamationTriangle,
  faExpandAlt,
  faRocket,
  faExpandArrowsAlt,
  faEye,
  faFileImage,
  faFileInvoiceDollar,
  faFilePdf,
  faFolder,
  faFolderOpen,
  faGrinSquintTears,
  faHome,
  faIdCard,
  faImages,
  faInfo,
  faLanguage,
  faMailBulk,
  faMoneyBill,
  faMoneyBillWave,
  faPhone,
  faPlus,
  faProjectDiagram,
  faQrcode,
  faQuestionCircle,
  faInfoCircle,
  faSave,
  faSignInAlt,
  faSignOutAlt,
  faStar,
  faStarHalf,
  faStarHalfAlt,
  faSync,
  faTasks,
  faTimes,
  faToolbox,
  faTrash,
  faTrashRestore,
  faUniversity,
  faUnlockAlt,
  faUpload,
  faUserClock,
  faUserCog,
  faUserSecret,
  faWindowClose,
  faFileCode,
  faBold,
  faListOl,
  faItalic,
  faWarning,
  faCalendar,
  faArrows,
  faArrowsSplitUpAndLeft,
  faArrowsUpDown,
  faBattery,
  faArrowRotateForward,
  faArrowRotateBackward,
  faFileInvoice,
  faFileCircleXmark,
} from '@fortawesome/free-solid-svg-icons';

import { faGithub, faLinkedin } from '@fortawesome/free-brands-svg-icons';
import { ServiceWorkerModule } from '@angular/service-worker';
import { environment } from '@env/environment';
import { LayoutModule } from '@feature/layout/layout.module';
import { HIGHLIGHT_OPTIONS, HighlightModule } from 'ngx-highlightjs';
import { KeycloakAngularModule, KeycloakService } from 'keycloak-angular';
import { initialize } from './init/app-init.factory';
import { ConfigInitService } from './init/config-init.service';
import { provideProtractorTestingSupport } from '@angular/platform-browser';
import { providePrimeNG } from 'primeng/config';

PlotlyViaCDNModule.setPlotlyVersion('2.28.0'); // can be `latest` or any version number (i.e.: '1.40.0')
PlotlyViaCDNModule.setPlotlyBundle('finance');
registerLocaleData(localeDe, 'de');

@NgModule({
  declarations: [AppComponent],
  imports: [
    AppRoutingModule,
    LayoutModule,
    KeycloakAngularModule,
    HighlightModule,
    ServiceWorkerModule.register('safety-worker.js', {
      // disable ngsw worker
      enabled: environment.production,
    }),
  ],
  providers: [
    providePrimeNG({
      theme: {
        preset: Aura,
      },
    }),
    { provide: APP_ID, useValue: 'serverApp' },
    { provide: LOCALE_ID, useValue: 'de' },
    ConfigInitService,
    provideAppInitializer(() => {
      const initializerFn = initialize(inject(KeycloakService), inject(ConfigInitService));
      return initializerFn();
    }),
    {
      provide: HIGHLIGHT_OPTIONS,
      useValue: {
        coreLibraryLoader: () => import('highlight.js/lib/core'),
        lineNumbersLoader: () => import('ngx-highlightjs/line-numbers'), // Optional, only if you want the line numbers
        languages: {
          json: () => import('highlight.js/lib/languages/json'),
        },
      },
    },
  ],
  exports: [],
  bootstrap: [AppComponent],
})
export class AppModule {
  constructor(library: FaIconLibrary) {
    // font awesome
    library.addIcons(
      faEdit,

      faVcard,
      faBattery,
      faDatabase,
      faAsterisk,
      faUser,
      faArrowRotateBackward,
      faArrowRotateForward,
      faKey,
      faArrowLeft,
      faIdCard,
      faAddressBook,
      faFileCode,
      faBold,
      faListOl,
      faItalic,
      faArrows,
      faArrowsUpDown,
      faArrowsSplitUpAndLeft,
      faCalendar,
      faFileInvoice,

      faPhone,
      faFileInvoiceDollar,
      faBirthdayCake,
      faMailBulk,
      faRocket,
      faBookOpen,
      faDoorClosed,
      faClock,
      faUserClock,
      faCopy,
      faSave,
      faInfo,
      faDollarSign,
      faTasks,
      faInfoCircle,
      faCalendar,
      faQuestionCircle,
      faMoneyBill,
      faEnvelope,
      faExclamation,
      faBookOpen,
      faGrinSquintTears,
      faUnlockAlt,
      faEye,
      faArrowDown,
      faArrowUp,
      faImages,
      faTimes,
      faConciergeBell,
      faExpandAlt,
      faExpandArrowsAlt,
      faCalendarAlt,
      faQrcode,
      faLanguage,
      faProjectDiagram,
      faMoneyBillWave,
      faChartLine,
      faFolder,
      faFolderOpen,
      faUserSecret,
      faBlog,
      faXmarksLines,
      faFileInvoiceDollar,
      faUniversity,
      faCheck,
      faExclamationTriangle,
      faSync,
      faDotCircle,
      faCircle,
      faDatabase,
      faUpload,
      faSignInAlt,
      faWindowClose,
      faEllipsisH,
      faFileImage,
      faStar,
      faStarHalf,
      faStarHalfAlt,
      faBuilding,
      faBars,
      faSignOutAlt,
      faHome,
      faToolbox,
      faUserCog,
      faCheckCircle,
      faLinkedin,
      faWarning,
      faDownload,
      faGithub,
      faPlus,
      faCog,
      faTrash,
      faFilePdf,
      faFileCircleXmark,
      faFileCode,
      faTrashRestore,
    );
  }
}
